# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-12 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('prodct_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('portfolio_name', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=100, null=True)),
                ('campaign_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bidding_strategy', models.CharField(blank=True, max_length=100, null=True)),
                ('placement', models.CharField(blank=True, max_length=100, null=True)),
                ('impressions', models.CharField(blank=True, max_length=100, null=True)),
                ('clicks', models.CharField(blank=True, max_length=100, null=True)),
                ('cost_per_click', models.CharField(blank=True, max_length=100, null=True)),
                ('spend', models.CharField(blank=True, max_length=100, null=True)),
                ('day7_total_sales', models.CharField(blank=True, max_length=100, null=True)),
                ('total_advertising_cost_of_sales', models.CharField(blank=True, max_length=100, null=True)),
                ('total_return_on_advertising_spend', models.CharField(blank=True, max_length=100, null=True)),
                ('day7_total_orders', models.CharField(blank=True, max_length=100, null=True)),
                ('day7_total_units', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
