# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-12 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonProduct',
            fields=[
                ('amz_prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_dimensions', models.DateField(blank=True, null=True)),
                ('shipping_weight', models.CharField(blank=True, max_length=100, null=True)),
                ('domestic_shipping', models.CharField(blank=True, max_length=100, null=True)),
                ('international_shipping', models.CharField(blank=True, max_length=100, null=True)),
                ('asin', models.CharField(blank=True, max_length=100, null=True)),
                ('upc', models.CharField(blank=True, max_length=100, null=True)),
                ('average_customer_review', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
