# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-12 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_amazonproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonproduct',
            name='asin',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='average_customer_review',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='domestic_shipping',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='international_shipping',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='product_dimensions',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='shipping_weight',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='upc',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
